/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { JobService } from "../job.service";
import { JobCreateInput } from "./JobCreateInput";
import { Job } from "./Job";
import { JobFindManyArgs } from "./JobFindManyArgs";
import { JobWhereUniqueInput } from "./JobWhereUniqueInput";
import { JobUpdateInput } from "./JobUpdateInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";
import { UberRequestFindManyArgs } from "../../uberRequest/base/UberRequestFindManyArgs";
import { UberRequest } from "../../uberRequest/base/UberRequest";
import { UberRequestWhereUniqueInput } from "../../uberRequest/base/UberRequestWhereUniqueInput";

export class JobControllerBase {
  constructor(protected readonly service: JobService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Job })
  async createJob(@common.Body() data: JobCreateInput): Promise<Job> {
    return await this.service.createJob({
      data: data,
      select: {
        assignedWorker: true,
        client: true,
        createdAt: true,
        description: true,
        endTime: true,
        id: true,
        jobType: true,
        price: true,
        startTime: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Job] })
  @ApiNestedQuery(JobFindManyArgs)
  async jobs(@common.Req() request: Request): Promise<Job[]> {
    const args = plainToClass(JobFindManyArgs, request.query);
    return this.service.jobs({
      ...args,
      select: {
        assignedWorker: true,
        client: true,
        createdAt: true,
        description: true,
        endTime: true,
        id: true,
        jobType: true,
        price: true,
        startTime: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Job })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async job(@common.Param() params: JobWhereUniqueInput): Promise<Job | null> {
    const result = await this.service.job({
      where: params,
      select: {
        assignedWorker: true,
        client: true,
        createdAt: true,
        description: true,
        endTime: true,
        id: true,
        jobType: true,
        price: true,
        startTime: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Job })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateJob(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() data: JobUpdateInput
  ): Promise<Job | null> {
    try {
      return await this.service.updateJob({
        where: params,
        data: data,
        select: {
          assignedWorker: true,
          client: true,
          createdAt: true,
          description: true,
          endTime: true,
          id: true,
          jobType: true,
          price: true,
          startTime: true,
          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Job })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteJob(
    @common.Param() params: JobWhereUniqueInput
  ): Promise<Job | null> {
    try {
      return await this.service.deleteJob({
        where: params,
        select: {
          assignedWorker: true,
          client: true,
          createdAt: true,
          description: true,
          endTime: true,
          id: true,
          jobType: true,
          price: true,
          startTime: true,
          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: JobWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        id: true,

        job: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        worker: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  async connectPayments(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateJob({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  async updatePayments(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateJob({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  async disconnectPayments(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateJob({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/uberRequests")
  @ApiNestedQuery(UberRequestFindManyArgs)
  async findUberRequests(
    @common.Req() request: Request,
    @common.Param() params: JobWhereUniqueInput
  ): Promise<UberRequest[]> {
    const query = plainToClass(UberRequestFindManyArgs, request.query);
    const results = await this.service.findUberRequests(params.id, {
      ...query,
      select: {
        createdAt: true,
        dropOffLocation: true,
        id: true,

        job: {
          select: {
            id: true,
          },
        },

        passenger: true,
        pickupLocation: true,
        requestTime: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/uberRequests")
  async connectUberRequests(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() body: UberRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      uberRequests: {
        connect: body,
      },
    };
    await this.service.updateJob({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/uberRequests")
  async updateUberRequests(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() body: UberRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      uberRequests: {
        set: body,
      },
    };
    await this.service.updateJob({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/uberRequests")
  async disconnectUberRequests(
    @common.Param() params: JobWhereUniqueInput,
    @common.Body() body: UberRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      uberRequests: {
        disconnect: body,
      },
    };
    await this.service.updateJob({
      where: params,
      data,
      select: { id: true },
    });
  }
}
